export const CHARACTERS = {
  A: 'a',
  B: 'b',
  C: 'c',
  D: 'd',
  E: 'e',
  F: 'f',
  G: 'g',
  H: 'h',
  I: 'i',
  J: 'j',
  K: 'k',
  L: 'l',
  M: 'm',
  N: 'n',
  QUIJOTE: 'ñ',
  O: 'o',
  P: 'p',
  Q: 'q',
  R: 'r',
  S: 's',
  T: 't',
  U: 'u',
  V: 'v',
  W: 'w',
  X: 'x',
  Y: 'y',
  Z: 'z',
}
export const VOWELS = [CHARACTERS.A, CHARACTERS.E, CHARACTERS.I, CHARACTERS.O, CHARACTERS.U]
export const CONSONANT = [
  CHARACTERS.B,
  CHARACTERS.C,
  CHARACTERS.D,
  CHARACTERS.F,
  CHARACTERS.G,
  CHARACTERS.H,
  CHARACTERS.J,
  CHARACTERS.K,
  CHARACTERS.L,
  CHARACTERS.M,
  CHARACTERS.N,
  CHARACTERS.QUIJOTE,
  CHARACTERS.P,
  CHARACTERS.Q,
  CHARACTERS.R,
  CHARACTERS.S,
  CHARACTERS.T,
  CHARACTERS.V,
  CHARACTERS.W,
  CHARACTERS.X,
  CHARACTERS.Y,
  CHARACTERS.Z,
]
